spring:
   application:
      name: Order-service-v2.6.5

server:
  port: 33021

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.204.3:10002/eureka/
  instance:
    preferIpAddress: true
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  #file: orderservice.log
  file: /var/kido/logs/orderservice.log
